#!/bin/bash
# Run a command and store its output in a variable
project=$(gcloud config get-value project)
project_num=$(gcloud projects describe $project --format="value(projectNumber)")

# Attach Roles to default serviceaccount
gcloud projects add-iam-policy-binding $project \
    --member="serviceAccount:service-$project_num@gcp-sa-pubsub.iam.gserviceaccount.com" \
    --role="roles/iam.serviceAccountTokenCreator"
